# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resdec', '0003_auto_20180717_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive')], default=b'A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InterestItemsNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resdec.Interest')),
            ],
        ),
        migrations.RemoveField(
            model_name='trendsitemsnames',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='variabilityenvironmentdata',
            name='path',
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive')], default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='variabilityenvironment',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive')], default=b'A', max_length=1),
        ),
        migrations.AddField(
            model_name='variabilityenvironmentdata',
            name='base_on',
            field=models.CharField(choices=[(b'F', b'Features'), (b'R', b'Ratings')], default=b'', max_length=1),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive')], default=b'A', max_length=1),
        ),
        migrations.AlterField(
            model_name='variabilityenvironmentdata',
            name='file',
            field=models.FileField(max_length=500, upload_to=b'user_data_uploaded'),
        ),
        migrations.AlterField(
            model_name='variabilityenvironmentdata',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'I', b'Inactive')], default=b'A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
        migrations.DeleteModel(
            name='TrendsItemsNames',
        ),
        migrations.AddField(
            model_name='interest',
            name='variability_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resdec.VariabilityEnvironment'),
        ),
    ]
