# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resdec', '0004_auto_20180724_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryUserItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('date_use', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variability_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resdec.VariabilityEnvironment')),
            ],
        ),
        migrations.AddField(
            model_name='variabilityenvironmentdata',
            name='separator',
            field=models.CharField(default=b'|', max_length=1),
        ),
        migrations.AlterField(
            model_name='variabilityenvironmentdata',
            name='base_on',
            field=models.CharField(choices=[(b'F', b'Features'), (b'G', b'Grouped Features'), (b'R', b'Ratings')], default=b'', max_length=1),
        ),
    ]
