# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-12 05:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdec', '0005_auto_20180727_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabilityenvironmentdata',
            name='feature_column',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='variabilityenvironmentdata',
            name='item_column',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='variabilityenvironmentdata',
            name='rating_column',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='variabilityenvironmentdata',
            name='base_on',
            field=models.CharField(choices=[(b'F', b'Features'), (b'R', b'Ratings')], default=b'', max_length=1),
        ),
    ]
