# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-28 20:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resdec', '0006_auto_20180812_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variabilityenvironmentdata',
            name='relationship_type',
        ),
    ]
