# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 17:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdec', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'user_photos/'),
        ),
    ]
