# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 20:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resdec', '0013_auto_20180917_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, upload_to=b'media/user_photos/'),
        ),
        migrations.AlterField(
            model_name='variabilityenvironmentdata',
            name='file',
            field=models.FileField(max_length=500, upload_to=b'media/user_data_uploaded/'),
        ),
    ]
